version: '3.1'
services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql

  magento2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPOSER_AUTH: $COMPOSER_AUTH
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/magento2-sample-data:/tmp/sample-data
      - ./app:/var/www/app
      - ./lib:/var/www/lib
      - ./data/magento-media:/var/www/pub/media
    depends_on:
      - mariadb
